// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpihuwgpcrmyfbhvvbty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaWh1d2dwY3JteWZiaHZ2YnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjY2NDQsImV4cCI6MjA2OTM0MjY0NH0.RbpwjaiPleRsmYWvJMAjgAIerVLDtupC3Ghk9rw-nxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});